meta_product_name: "Ferme de Beau Printemps"
meta_title: "Ferme de Beau Printemps"
meta_description: "Relevant description"
meta_image: "clock.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
